State = [
    {"name": "炼气期", "level": 9, "exp": 30},
    {"name": "筑基期", "level": 9, "exp": 50},
    {"name": "金丹期", "level": 9, "exp": 70},
    {"name": "元婴期", "level": 9, "exp": 90},
    {"name": "化神期", "level": 9, "exp": 110},
    {"name": "合道期", "level": 9, "exp": 150},
    {"name": "地仙期", "level": 9, "exp": 200},
    {"name": "天仙期", "level": 9, "exp": 1000},
    {"name": "金仙期", "level": 9, "exp": 2000},
    {"name": "太乙金仙期", "level": 9, "exp": 3000},
    {"name": "大罗金仙期", "level": 9, "exp": 4000},
    {"name": "准圣", "level": 9, "exp": 5000},
    {"name": "圣人", "level": 9, "exp": 10000},
    {"name": "天道", "level": 9, "exp": 0},
]